import { FixtureDto } from "@/dtos/npl/teams-dto";

export const nplFixtures: FixtureDto[] = [
  {
    team1: {
      id: 1,
      name: "Biratnagar Kings",
      shortName: "BIK",
      image: "/deleteable/npl/BIK.jpg",
      primaryColor: "#1A1A1A",
      secondaryColor: "#FF5733",
    },
    team2: {
      id: 2,
      name: "Janakpur Bolts",
      shortName: "JAB",
      image: "/deleteable/npl/JAB.png",
      primaryColor: "#3498DB",
      secondaryColor: "#2ECC71",
    },
    isFinished: true,
    venue: "TU Ground",
    date: "2024-11-30T12:00:00",
    wonBy: "Janakpur Bolts",
  },
  {
    team1: {
      id: 3,
      name: "Kathmandu Gurkhas",
      shortName: "KAG",
      image: "/deleteable/npl/KAG.png",
      primaryColor: "#8E44AD",
      secondaryColor: "#34495E",
    },
    team2: {
      id: 4,
      name: "Chitwan Rhinos",
      shortName: "CHR",
      image: "/deleteable/npl/CHR.png",
      primaryColor: "#E74C3C",
      secondaryColor: "#2C3E50",
    },
    isFinished: true,
    venue: "Pokhara Stadium",
    date: "2024-12-02T09:00:00",
    wonBy: "Chitwan Rhinos",
  },
  {
    team1: {
      id: 2,
      name: "Janakpur Bolts",
      shortName: "JAB",
      image: "/deleteable/npl/JAB.png",
      primaryColor: "#3498DB",
      secondaryColor: "#2ECC71",
    },
    team2: {
      id: 5,
      name: "Karnali Yaks",
      shortName: "KAY",
      image: "/deleteable/npl/KAY.png",
      primaryColor: "#1ABC9C",
      secondaryColor: "#16A085",
    },
    isFinished: true,
    venue: "Chitwan Stadium",
    date: "2024-12-02T13:00:00",
    wonBy: "Janakpur Bolts",
  },
  {
    team1: {
      id: 6,
      name: "Sudurpaschim Royals",
      shortName: "SPR",
      image: "/deleteable/npl/SPR.png",
      primaryColor: "#F39C12",
      secondaryColor: "#D35400",
    },
    team2: {
      id: 1,
      name: "Biratnagar Kings",
      shortName: "BIK",
      image: "/deleteable/npl/BIK.jpg",
      primaryColor: "#1A1A1A",
      secondaryColor: "#FF5733",
    },
    isFinished: false,
    venue: "Dhangadhi Stadium",
    date: "2024-12-03T09:00:00",
    wonBy: "",
  },
  {
    team1: {
      id: 5,
      name: "Karnali Yaks",
      shortName: "KAY",
      image: "/deleteable/npl/KAY.png",
      primaryColor: "#1ABC9C",
      secondaryColor: "#16A085",
    },
    team2: {
      id: 6,
      name: "Sudurpaschim Royals",
      shortName: "SPR",
      image: "/deleteable/npl/SPR.png",
      primaryColor: "#F39C12",
      secondaryColor: "#D35400",
    },
    isFinished: false,
    venue: "Pokhara Stadium",
    date: "2024-12-04T13:00:00",
    wonBy: "",
  },
  {
    team1: {
      id: 3,
      name: "Kathmandu Gurkhas",
      shortName: "KAG",
      image: "/deleteable/npl/KAG.png",
      primaryColor: "#8E44AD",
      secondaryColor: "#34495E",
    },
    team2: {
      id: 7,
      name: "Lumbini Lions",
      shortName: "LUL",
      image: "/deleteable/npl/LUL.png",
      primaryColor: "#C0392B",
      secondaryColor: "#ECF0F1",
    },
    isFinished: false,
    venue: "Kathmandu Stadium",
    date: "2024-12-05T09:00:00",
    wonBy: "",
  },
  {
    team1: {
      id: 2,
      name: "Janakpur Bolts",
      shortName: "JAB",
      image: "/deleteable/npl/JAB.png",
      primaryColor: "#3498DB",
      secondaryColor: "#2ECC71",
    },
    team2: {
      id: 8,
      name: "Pokhara Avengers",
      shortName: "POA",
      image: "/deleteable/npl/POA.png",
      primaryColor: "#2980B9",
      secondaryColor: "#D35400",
    },
    isFinished: false,
    venue: "Dhangadhi Stadium",
    date: "2024-12-06T09:00:00",
    wonBy: "",
  },
  {
    team1: {
      id: 1,
      name: "Biratnagar Kings",
      shortName: "BIK",
      image: "/deleteable/npl/BIK.jpg",
      primaryColor: "#1A1A1A",
      secondaryColor: "#FF5733",
    },
    team2: {
      id: 4,
      name: "Chitwan Rhinos",
      shortName: "CHR",
      image: "/deleteable/npl/CHR.png",
      primaryColor: "#E74C3C",
      secondaryColor: "#2C3E50",
    },
    isFinished: false,
    venue: "Biratnagar Stadium",
    date: "2024-12-07T13:00:00",
    wonBy: "",
  },
];
