export const npmTeams = [
  {
    id: 1,
    name: "Janakpurbolts",
    image: "/deleteable/npl/JAB.png",
    shortName: "JAB",
    primaryColor: "#1A2745",
    secondaryColor: "#d94c9c",
  },
  {
    id: 2,
    name: "Biratnagar Kings",
    image: "/deleteable/npl/BIK.jpg",
    shortName: "BIK",
    primaryColor: "#1E2B43",
    secondaryColor: "#e0b51b",
  },
  {
    id: 3,
    name: "Chitwan Rhinos",
    image: "/deleteable/npl/CHR.png",
    shortName: "CHR",
    primaryColor: "#322B37",
    secondaryColor: "#e6ab91",
  },
  {
    id: 4,
    name: "Pokhara Avengers",
    image: "/deleteable/npl/POA.png",
    shortName: "POA",
    primaryColor: "#1A2745",
    secondaryColor: "#d94c9c",
  },
  {
    id: 5,
    name: "Kathmandu Gorkhas",
    image: "/deleteable/npl/KAG.png",
    shortName: "KAG",
    primaryColor: "#1A2745",
    secondaryColor: "#d94c9c",
  },
  {
    id: 6,
    name: "Lumbini Lions",
    image: "/deleteable/npl/LUL.png",
    shortName: "LUL",
    primaryColor: "#1A2745",
    secondaryColor: "#d94c9c",
  },
  {
    id: 7,
    name: "Karnali Yaks",
    image: "/deleteable/npl/KAY.png",
    shortName: "KAY",
    primaryColor: "#1A2745",
    secondaryColor: "#d94c9c",
  },
  {
    id: 8,
    name: "Sudur paschim royals",
    image: "/deleteable/npl/SPR.png",
    shortName: "SPR",
    primaryColor: "#FFFFFF",
    secondaryColor: "#d94c9c",
  },
];
