import type { Metadata } from "next";
import { Bitter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const inter = Bitter({
  subsets: ["cyrillic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="mt-[112px]"></div>
        {children}
      </body>
    </html>
  );
}
